### PR TITLE
Fix record serialization when using JacksonAnnotationExtension

### LINKED ISSUE #176: Cannot Deserialize JSON with `@JsonProperty`-annotated Record fields
I'm encountering an issue when using Jackson-jr with annotation support to handle record classes that map to JSON with snake_case field names. While serialization works as expected, deserialization of the same JSON back into the record fails.

To illustrate the problem, I created a minimal reproducer: [jackson-jr-annotations-reproducer](https://github.com/juulhobert/jackson-jr-annoations-reproducer).

**Steps to Reproduce:**
Use a record class where fields are annotated with @JsonProperty to specify the snake_case equivalent of the field name. Serialize an instance of the record class to JSON using Jackson-jr (with annotation support). Attempt to deserialize the resulting JSON back into the record class.

Expected Behavior:
The JSON should deserialize correctly into the record class, matching fields based on the @JsonProperty annotations.

Actual Behavior:
Deserialization fails with an exception
image

Environment:
Jackson-jr version: 2.18.1
Java version: 21

Reproducer Link:
https://github.com/juulhobert/jackson-jr-annoations-reproducer

### PR DESCRIPTION
**Pull request by TomaszGaweda**
This PR fixes record serialization and deserialization when using Java Records with JacksonAnnotationExtension

Fixes #176

### CODE REVIEW

File: jr-annotation-support/src/main/java/com/fasterxml/jackson/jr/annotationsupport/AnnotationBasedIntrospector.java [hunk 1]
```diff
@@ -147,21 +195,31 @@ protected POJODefinition.Prop[] _pruneProperties(boolean sortProperties)
...
-                    renamed = new LinkedList<APropBuilder>();
+            String explicitName = prop.findPrimaryExplicitName(_forSerialization);
+            if (explicitName != null) {
+                APropBuilder newProp = prop.withName(explicitName);
+                if (keepPropertyOrderForRecord) {
+                    APropBuilder orig = _props.get(explicitName);
+                    if (orig != null) {
+                        newProp = APropBuilder.merge(orig, newProp);
+                    }
+                    ((IndexedMap<String, APropBuilder>) _props)
```
Comment (TomaszGaweda) [inline jr-annotation-support/src/main/java/com/fasterxml/jackson/jr/annotationsupport/AnnotationBasedIntrospector.java]: rationale: we don't want to change position, because of the renaming

**Comment by TomaszGaweda** [comment]
Hi @cowtowncoder, I'd very appreciate if you could take a look at this PR (of course nothing urgent). Thanks in advance!

**Comment by cowtowncoder** [comment]
@TomaszGaweda sorry for delay, hoping to review this week (having to focus on 3.0.0-rc10 first). Just thought I'll add a note to let you know this is on my radar, todo list.

**Comment by TomaszGaweda** [comment]
Thanks a lot @cowtowncoder for the update and no worries :)

File: jr-annotation-support/src/main/java/com/fasterxml/jackson/jr/annotationsupport/IndexedMap.java [hunk 2]
```diff
@@ -0,0 +1,180 @@
...
+import java.util.Collection;
+import java.util.Iterator;
+import java.util.LinkedHashSet;
+import java.util.Map;
+import java.util.Set;
+
+import static java.util.stream.Collectors.toSet;
+
+/**
+ * Map used when we need to maintain insertion index.
```
Comment (cowtowncoder) [inline jr-annotation-support/src/main/java/com/fasterxml/jackson/jr/annotationsupport/IndexedMap.java:15]: Should expand a bit to indicate why JDK `LinkedHashMap` wouldn't work?

Comment (TomaszGaweda) [reply jr-annotation-support/src/main/java/com/fasterxml/jackson/jr/annotationsupport/IndexedMap.java:15]: Added here: https://github.com/FasterXML/jackson-jr/pull/207/commits/4ec9eeca94d6a566e6c5ebed98dbe76e51003b85

File: jr-annotation-support/src/main/java/com/fasterxml/jackson/jr/annotationsupport/IndexedMap.java [hunk 3]
```diff
@@ -0,0 +1,183 @@
...
+    /**
+     * Replaces entry at the index of {@code oldKey} with a new entry: {@code newKey, value}.
+     */
+    public void replaceAtIndexOf(K oldKey, K newKey, V value) {
+        boolean stop = false;
+        for (int index = 0; index < entries.size() && !stop; index++) {
+            Entry<K, V> kvEntry = entries.get(index);
+            if (kvEntry.getKey().equals(oldKey)) {
+                entries.set(index, new SimpleEntry<>(newKey, value));
+                stop = true;
```
Comment (cowtowncoder) [inline jr-annotation-support/src/main/java/com/fasterxml/jackson/jr/annotationsupport/IndexedMap.java]: Why not just use `return` (or, `break`) instead of a flag?

Comment (cowtowncoder) [reply jr-annotation-support/src/main/java/com/fasterxml/jackson/jr/annotationsupport/IndexedMap.java]: Actually I'll just change. :)

File: jr-objects/src/main/java/com/fasterxml/jackson/jr/ob/impl/BeanReader.java [hunk 4]
```diff
@@ -149,9 +150,40 @@ private Object readRecord(JSONReader r, JsonParser p) throws Exception {
             Object value = prop.getReader().readNext(r, p);
             values[prop.getIndex()] = value;
         }
+        for (int i = 0; i < values.length; i++) {
```
Comment (cowtowncoder) [inline jr-objects/src/main/java/com/fasterxml/jackson/jr/ob/impl/BeanReader.java]: This would require a comment -- explaining that for primitive types `null`s not allowed.

File: jr-objects/src/main/java/com/fasterxml/jackson/jr/ob/impl/BeanReader.java [hunk 5]
```diff
@@ -149,9 +150,40 @@ private Object readRecord(JSONReader r, JsonParser p) throws Exception {
...
+            if (values[i] == null) {
+                for (BeanPropertyReader prop : _propsByName.values()) {
```
Comment (cowtowncoder) [inline jr-objects/src/main/java/com/fasterxml/jackson/jr/ob/impl/BeanReader.java]: This is rather inefficient with n*n complexity (although I guess mostly n if no `null`s from missing entries?). Would be good to have either direct lookup (ordered array/List of props by index), or...

actually better idea, I think -- for records, pre-create `Object[]` with defaults for primitive values (instead of `null`s for regular object values)
Then something like:

    final Object[] values = Arrays.copyOf(preset, preset.length);

and avoid post-scanning?

File: jr-objects/src/main/java/com/fasterxml/jackson/jr/ob/impl/BeanReader.java [hunk 6]
```diff
@@ -149,9 +150,40 @@ private Object readRecord(JSONReader r, JsonParser p) throws Exception {
...
+        }
+        if (aClass.equals(boolean.class)) {
+            return Boolean.FALSE;
+        }
+        if (aClass.equals(short.class)) {
+            return (short) 0;
+        }
+        if (aClass.equals(char.class)) {
+            return (char) 0;
+        }
```
Comment (cowtowncoder) [inline jr-objects/src/main/java/com/fasterxml/jackson/jr/ob/impl/BeanReader.java:202]: Missing `float.class` and `double.class`?

**Review by cowtowncoder — COMMENTED** [review]
Pretty good; we are almost there! Couple of small changes needed and we are good to go!

File: jr-objects/src/main/java/com/fasterxml/jackson/jr/ob/impl/BeanReader.java (hunk 6 above)
Comment (cowtowncoder) [reply jr-objects/src/main/java/com/fasterxml/jackson/jr/ob/impl/BeanReader.java:202]: (and `byte.class`)

Added.

File: jr-objects/src/main/java/com/fasterxml/jackson/jr/ob/impl/BeanReader.java (hunk 5 above)
Comment (cowtowncoder) [reply jr-objects/src/main/java/com/fasterxml/jackson/jr/ob/impl/BeanReader.java]: @TomaszGaweda does this make sense? If not, I can try to explain in more detail.

Comment (TomaszGaweda) [reply jr-objects/src/main/java/com/fasterxml/jackson/jr/ob/impl/BeanReader.java]: Hey @cowtowncoder ! Yes, it makes sense, 2n is definetely better than n^2. I will work on this PR this week, had very limited time last week unfortunatelly

Comment (TomaszGaweda) [reply jr-objects/src/main/java/com/fasterxml/jackson/jr/ob/impl/BeanReader.java]: Done: [`8b9daf9` (#207)](https://github.com/FasterXML/jackson-jr/pull/207/commits/8b9daf913e26dc658a854861df33eb15b97d7935)

File: jr-objects/src/main/java/com/fasterxml/jackson/jr/ob/impl/BeanReader.java (hunk 4 above)
Comment (TomaszGaweda) [reply jr-objects/src/main/java/com/fasterxml/jackson/jr/ob/impl/BeanReader.java]: Done

File: jr-objects/src/main/java/com/fasterxml/jackson/jr/ob/impl/BeanReader.java (hunk 5 above)
Comment (cowtowncoder) [reply jr-objects/src/main/java/com/fasterxml/jackson/jr/ob/impl/BeanReader.java]: That was quick, thank you! Will review later today.

**Comment by TomaszGaweda** [comment]
Thank you a lot @cowtowncoder for review and your help!
